[project]
name = "docrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.45.0",
    "python-dotenv>=1.1.1",
    "httpx>=0.27.0",
]
